name: Build and deploy Zola website
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          submodules: 'recursive'
          force-depth: 0
      - name: Build site
        run: |
          curl -fsSL "https://api.github.com/repos/getzola/zola/releases/latest"  | jq -r '.assets[] | select(.name | test("zola-.*-x86_64.*musl.tar.gz")).browser_download_url' | xargs curl -fsSL | tar xzvf -
          ./zola build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: public/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
